# react-front-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-front
  template:
    metadata:
      labels:
        app: react-front
    spec:
      containers:
      - name: react-front
        image: gcr.io/annular-form-401215/front-pasajeros:v3
        ports:
        - containerPort: 3000
