# front-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-front
spec:
  selector:
    app: react-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

